BEGIN;

-- Facturation / Paiements
TRUNCATE encaissement_client RESTART IDENTITY CASCADE;
TRUNCATE facture_client RESTART IDENTITY CASCADE;

-- Ventes
TRUNCATE commande_client RESTART IDENTITY CASCADE;
TRUNCATE proforma_client RESTART IDENTITY CASCADE;

-- Stock
TRUNCATE mouvement_stock RESTART IDENTITY CASCADE;
TRUNCATE lot RESTART IDENTITY CASCADE;
TRUNCATE type_mouvement RESTART IDENTITY CASCADE;

-- Achats
TRUNCATE ligne_demande_achat RESTART IDENTITY CASCADE;
TRUNCATE demande_achat RESTART IDENTITY CASCADE;
TRUNCATE departement RESTART IDENTITY CASCADE;

-- Sécurité & accès
TRUNCATE delegation_temporaire RESTART IDENTITY CASCADE;
TRUNCATE utilisateur_depot RESTART IDENTITY CASCADE;
TRUNCATE utilisateur_applicatif RESTART IDENTITY CASCADE;
TRUNCATE profil_utilisateur RESTART IDENTITY CASCADE;

TRUNCATE role_permission RESTART IDENTITY CASCADE;
TRUNCATE permission RESTART IDENTITY CASCADE;
TRUNCATE fonctionnalite RESTART IDENTITY CASCADE;
TRUNCATE module RESTART IDENTITY CASCADE;
TRUNCATE role RESTART IDENTITY CASCADE;

TRUNCATE utilisateur RESTART IDENTITY CASCADE;

-- Référentiels métier
TRUNCATE tarif RESTART IDENTITY CASCADE;
TRUNCATE article RESTART IDENTITY CASCADE;
TRUNCATE categorie_article RESTART IDENTITY CASCADE;
TRUNCATE unite_mesure RESTART IDENTITY CASCADE;
TRUNCATE client RESTART IDENTITY CASCADE;
TRUNCATE type_client RESTART IDENTITY CASCADE;
TRUNCATE fournisseur RESTART IDENTITY CASCADE;

-- Organisation
TRUNCATE emplacement RESTART IDENTITY CASCADE;
TRUNCATE depot RESTART IDENTITY CASCADE;
TRUNCATE site RESTART IDENTITY CASCADE;
TRUNCATE societe RESTART IDENTITY CASCADE;

-- Référentiels transverses
TRUNCATE methode_gestion RESTART IDENTITY CASCADE;
TRUNCATE mode_paiement RESTART IDENTITY CASCADE;
TRUNCATE devise RESTART IDENTITY CASCADE;
TRUNCATE ville RESTART IDENTITY CASCADE;

COMMIT;
